#
# Copyright (C) 2026 bsatou
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=shadcnui Theme Configuration
LUCI_DEPENDS:=+luci-base +luci-theme-shadcnui +curl +jsonfilter
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-shadcnui-config
PKG_VERSION:=0.3.3
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=bsatou

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
