#
# Copyright (C) 2025 NoobLk
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Noobwrt Theme
LUCI_DEPENDS:=+wget +jsonfilter
PKG_VERSION:=1.1.7
PKG_RELEASE:=1

CONFIG_LUCI_CSSTIDY:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
