#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service() {
	local enabled port
	config_load cf_dns_speedtest
	config_get_bool enabled config enabled 0
	[ "$enabled" = 1 ] || return 0
	[ -s /var/lib/cf-dns-speedtest/mosdns.yaml ] || /usr/bin/cf-dns-speedtest apply
	procd_open_instance
	procd_set_param command /usr/bin/mosdns start -c /var/lib/cf-dns-speedtest/mosdns.yaml
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="65535 65535"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger cf_dns_speedtest
}

reload_service() {
	stop
	start
}
