# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for xkcptun
LUCI_DEPENDS:=+xkcptun

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=Dengfeng Liu <liudf0716@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
