#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

NAME=devgate

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/devgatectrl
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger 'devgate'
}

reload_service() {
	touch "/var/$NAME.reload"
	pidof devgatectrl >/dev/null 2>&1 || start_service
	return 0
}

stop_service(){
	local pids
	pids="$(pidof devgatectrl 2>/dev/null)"
	[ -n "$pids" ] && kill $pids >/dev/null 2>&1
	[ -x /usr/bin/devgate ] && /usr/bin/devgate stop || true
}
