config wifidogx 'common'
	option external_interface 'wan'
	option check_interval '60'
	option client_timeout '60'
	option wired_passed '1'
	option enabled '1'
	option log_level '0'
	option js_filter '1'
	option auth_server_mode 'local'
	option enable_anti_nat '0'
	option ttl_values '64,128,255'
	option ap_device_id 'AW85844955CC7D742A339'
	option ap_mac_address '5C-C7-D7-42-A3-39'
	option ap_longitude '116.395000'
	option ap_latitude '039.911000'
	option disable_portal_auth '0'
	option enable_privileged_ops '0'
	option privileged_ops_secret 'chawrt@2026'
	option device_id 'AW58534605CC7D742A339'
	option local_portal 'https://qq.com'

config gateway 'apfree'
	option gateway_name 'br-lan'
	option gateway_channel 'apfree'
	option gateway_auth_enabled '1'
	option gateway_id '5CC7D742A336'
	option gateway_subnetv4 '192.168.8.1/24'

config auth 'local'
	option auth_server_hostname '192.168.8.109'
	option auth_server_port '8001'
	option auth_server_path '/wifidog/'

config longconn 'openclaw'
	option long_conn_mode 'ws'
	option ws_server_hostname '192.168.8.109'
	option ws_server_port '8001'
	option ws_server_path '/ws/wifidogx'
