#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-3.0-or-later

USE_PROCD=1
START=96
STOP=9

RUNTIME_DIR=/tmp/smartsafehub
PROG=/usr/libexec/smartsafehub-firmware

start_service() {
	mkdir -p "$RUNTIME_DIR" || return 1
	procd_open_instance
	procd_set_param command "$PROG" daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger smartsafehub
}
