#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.luxe >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.luxe=/luci-static/luxe
		set luci.main.mediaurlbase=/luci-static/luxe
		commit luci
	EOF
fi

exit 0
