#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

_get_global_enabled() {
	config_get_bool _GLOBAL_ENABLED "$1" "enabled" 0
}

start_service() {
	config_load "linkback"
	
	local _GLOBAL_ENABLED=0
	config_foreach _get_global_enabled "global"
	[ "$_GLOBAL_ENABLED" -eq 1 ] || return 0

	procd_open_instance "main"
	procd_set_param command /usr/sbin/linkbackd
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "linkback"
}
